version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/home/backend/app
      - /home/backend/app/node_modules
    ports:
      - "3002:3002"
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - ./backend/.env
    networks:
      - docker-net
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/home/frontend/app
      - /home/frontend/app/node_modules
    networks:
      - docker-net
  postgres_db:
    container_name: postgres_db
    image: postgres:12
    restart: always
    ports: 
      - "5432:5432"
    networks:
      - docker-net
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_DB: postgres
      PGDATA: /tmp
    volumes:
      - ./postgres/data:/var/lib/postgresql/data


networks:
  docker-net:
    driver: bridge